<?php

/**
 * @var \AHT\Product\Block\Edit $block
 */

?>

<form action="<?= $block->getUrl('product/index/save') ?>" method="post">
    <label for="name">Name</label>
    <input type="text" name="name" id="name" placeholder="Type Name Here">

    <label for="post_content">Content</label>
    <textarea name="post_content" id="post_content" cols="30" rows="10" placeholder="Type Content here"></textarea>

    <input type="submit" value="Save" />
</form>